AWSTemplateFormatVersion: '2010-09-09'
Description: Public S3 Bucket Created. Contains the source Orders PDF.

Resources:
  WareHouseOrders:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  WareHousePolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: 'WareHouseOrders'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:*'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: 'WareHouseOrders'
                  - '/*' 

  UploadObjectLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt UploadObjectLambdaFunctionRole.Arn
      FunctionName: UploadObjectLambdaFunction
      Environment:
        Variables:
          BUCKET_NAME: !Ref WareHouseOrders
      Runtime: python3.12
      Timeout: 60
      Code:
        ZipFile: |
          import json
          import os
          import urllib.request
          import boto3
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def send_response(event, context, status, response_data, reason=None):
              body = json.dumps({
                  'Status': status,
                  'Reason': reason or str(response_data),
                  'StackId': event['StackId'],
                  'RequestId': event['RequestId'],
                  'LogicalResourceId': event['LogicalResourceId'],
                  'PhysicalResourceId': event.get('PhysicalResourceId', context.log_stream_name),
                  'Data': response_data
              })
              req = urllib.request.Request(event['ResponseURL'], data=body.encode(), method='PUT')
              req.add_header('Content-Type', '')
              urllib.request.urlopen(req)

          def lambda_handler(event, context):
              s3_client = boto3.client('s3')
              logger.info("Lambda function started...")
              bucket_name = os.environ['BUCKET_NAME']

              try:
                  object_key = event['ResourceProperties']['ObjectKey']
                  source_url = event['ResourceProperties']['SourceUrl']
                  request_type = event['RequestType']

                  logger.info(f"Request Type: {request_type}")
                  logger.info(f"Object Key: {object_key}")
                  logger.info(f"Source URL: {source_url}")

                  if request_type == 'Create' or request_type == 'Update':
                      response = urllib.request.urlopen(source_url)
                      object_data = response.read()
                      s3_client.put_object(Body=object_data, Bucket=bucket_name, Key=f'downloads/{object_key}', ContentType='application/pdf', ContentDisposition='inline')
                      s3_flag_url = "https://immersionday-workshops-trendmicro.s3.amazonaws.com/boringpaperco/bucketfiles/secret.txt"
                      response = urllib.request.urlopen(s3_flag_url)
                      secret_data = response.read()
                      s3_client.put_object(Body=secret_data, Bucket=bucket_name, Key='secret.txt', ContentType='text/plain', ContentDisposition='inline')
                      send_response(event, context, 'SUCCESS', {'Status': 'SUCCESS', 'ObjectKey': object_key})

                  elif request_type == 'Delete':
                      resource_s3 = boto3.resource('s3')
                      bucket = resource_s3.Bucket(bucket_name)
                      bucket.objects.all().delete()
                      send_response(event, context, 'SUCCESS', {'Status': 'SUCCESS', 'ObjectKey': bucket_name})

                  else:
                      raise ValueError(f"Unsupported request type: {request_type}")

              except Exception as e:
                  logger.error(f"Error: {str(e)}")
                  send_response(event, context, 'FAILED', {}, reason=str(e))

  UploadObjectLambdaFunctionRole:
    Type: AWS::IAM::Role
    DependsOn:
      - "WareHousePolicy"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: UploadObjectLambdaFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:DeleteObject'
                Resource:
                  - !Sub "arn:aws:s3:::${WareHouseOrders}"
                  - !Sub "arn:aws:s3:::${WareHouseOrders}/*"
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: "*"

Outputs:
  BoringPaperCoBucket:
    Description: Boring Paper Company WareHouse Orders Bucket
    Value: !Ref WareHouseOrders