AWSTemplateFormatVersion: '2010-09-09'
Description: Public S3 Bucket Created. Contains the source Orders PDF.

Resources:
  WareHouseOrders:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  WareHousePolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: 'WareHouseOrders'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:*'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: 'WareHouseOrders'
                  - '/*' 

Outputs:
  BoringPaperCoBucket:
    Description: Boring Paper Company WareHouse Orders Bucket
    Value: !Ref WareHouseOrders